//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPOInv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equip
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string num { get; set; }
        public string cab { get; set; }
    }
}
